<a href="https://colab.research.google.com/github/nus-sps/workshops.tfi.data-visualisation/blob/main/python_basics_some_fundamentals_exercises_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basic Exercises

## Question 1 

Predict the output of the following code blocks?
   Run them in Colab to check if your predictions were correct?

   **Note:** You might have to look on the internet for the meaning of some symbols (such as `/` and `%`)

In [30]:
7 / 3 == 7 / 3.0

True

In [31]:
'nesia' in 'Indonesia'

True

In [32]:
(2 + 3) == 5

True

In [33]:
2 + 3 == 5

True

In [34]:
"2" + "3" == "5"

False

In [35]:
11 % 3

2

In [36]:
1 < 2 and 11 >= 9

True

In [37]:
2 > 5 or (1 < 2 and 11 >= 9)

True

## Question 2



Modify the above code to print ‘Hello Hello Hello Hello Batman’ when the name is ‘Batman.’

In [38]:
name = 'Batman'

if name == 'Batman':
   print('Hello '*5 + 'Batman!')
else:
   print('Hello World!')

Hello Hello Hello Hello Hello Batman!


Modify the code to respond to Robin instead of Batman.

In [54]:
name = 'Robin'

if name == 'Robin':
   print('Hello '*5 + 'Robin!')
else:
   print('Hello World!')

Hello Hello Hello Hello Hello Robin!


## Question 3

The following code has a few bugs; fix them!


In [40]:
import math
x,y = 3,4
z = math.sqrt(x**2 + y**2)
print(x,y,z)

3 4 5.0


## Question 4



In [41]:
import numpy as np

my_np_list = np.array([182, 269, 341, 410, 523,
                       697, 728, 856, 948, 101,
                       1120, 1272, 1312, 1460, 1564,
                       1642, 1717, 1816, 1923, 2087])                

1. What is the number in the 4th position in the array?

In [42]:
my_np_list[3]

410

2. What is the last number in the array?


In [43]:
my_np_list[-1]

2087

3. What are the first 3 values?


In [44]:
my_np_list[:3]

array([182, 269, 341])

4. What are the values from the 4th to the 10th position? (This should include the numbers at the 4th and 10th positions.)


In [45]:
my_np_list[3:10]

array([410, 523, 697, 728, 856, 948, 101])

5. What are the values in the list greater than 500?


In [46]:
my_np_list[my_np_list > 500]

array([ 523,  697,  728,  856,  948, 1120, 1272, 1312, 1460, 1564, 1642,
       1717, 1816, 1923, 2087])

7. Use the 'hidden' numpy functions `max()`, `min()`, `mean()` and `std()` to find the maximum, minimum, mean and standard deviation of the values of the numpy array.


In [47]:
my_np_list.max()

2087

In [48]:
my_np_list.min()

101

In [49]:
my_np_list.mean()

1048.4

In [50]:
my_np_list.std()

612.5768849703685

8. Make all the numbers less than 500 equal to zero!

In [51]:
my_np_list[my_np_list < 500] = 0

In [52]:
my_np_list                        # Did it work?

array([   0,    0,    0,    0,  523,  697,  728,  856,  948,    0, 1120,
       1272, 1312, 1460, 1564, 1642, 1717, 1816, 1923, 2087])

6. What are the values in the list greater than 500 **and** less than 1000?

**Note** 
- You cannot use '`and`' how arrays are setup internally! You need to use '`&`'.
- If it was an '`or`' the symbol will be '`|`' so that: 
```
(my_np_list > 500) | (my_np_list < 1000)
```

In [53]:
my_np_list[(my_np_list > 500) & (my_np_list < 1000)]

array([523, 697, 728, 856, 948])